Remove unused IntraProcessMessage
ros2/rcl_interfaces pull request #89
Opened 2020-03-06 02:10 UTC by brawner

IntraProcessMessage is no longer used except as a dummy message in rclcpp tests. This removes the message from rcl_interfaces and creates an empty message in test_msgs for those rclcpp tests. rclcpp doesn't depend on common_interfaces, but it already depended on test_msgs so this doesn't change its dependency count.

If reusing common_interfaces/empty.msg is better than creating an empty message I can switch to that instead.

2020-03-06 02:13 UTC, brawner commented
See also https://github.com/ros2/rclcpp/pull/1017

2020-03-06 02:19 UTC, brawner commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9550)](http://ci.ros2.org/job/ci_linux/9550/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5253)](http://ci.ros2.org/job/ci_linux-aarch64/5253/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7799)](http://ci.ros2.org/job/ci_osx/7799/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9472)](http://ci.ros2.org/job/ci_windows/9472/)

2020-03-06 18:13 UTC, ivanpauno requested changes
Can you move the `Dummy` msg here https://github.com/ros2/test_interface_files/tree/master/msg?
Thanks!

2020-03-06 18:32 UTC, dirk-thomas commented
Creating a `Dummy.msg` for this case seems overkill. If the tests can use an existing message definition instead that would be preferred. If they can't it would be good to state the rationale why.

2020-03-06 20:03 UTC, brawner commented
Thanks @ivanpauno for the suggestion. It looks like there is already an Empty message there, so I'm going to use that instead for rclcpp. Latest commit removes Dummy.

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9558)](http://ci.ros2.org/job/ci_linux/9558/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5260)](http://ci.ros2.org/job/ci_linux-aarch64/5260/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7804)](http://ci.ros2.org/job/ci_osx/7804/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9479)](http://ci.ros2.org/job/ci_windows/9479/)

2020-03-06 21:07 UTC, wjwwood approved these changes

2020-03-09 13:41 UTC, ivanpauno approved these changes

2020-03-19 19:49 UTC, brawner commented
Retesting:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9703)](http://ci.ros2.org/job/ci_linux/9703/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=5362)](http://ci.ros2.org/job/ci_linux-aarch64/5362/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7912)](http://ci.ros2.org/job/ci_osx/7912/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9601)](http://ci.ros2.org/job/ci_windows/9601/)

2020-03-20 00:22 UTC, brawner commented
@ivanpauno @wjwwood The tests now pass. If someone could merge this for me, I would appreciate it.

2020-03-20 19:36 UTC, merged

2020-03-20 19:37 UTC, ivanpauno commented
> @ivanpauno @wjwwood The tests now pass. If someone could merge this for me, I would appreciate it.

Merged both this PR and the one in `rclcpp`.

2020-03-20 19:41 UTC, brawner commented
Thank you!

On Fri, Mar 20, 2020 at 12:37 PM Ivan Santiago Paunovic <
notifications@github.com> wrote:

> @ivanpauno <https://github.com/ivanpauno> @wjwwood
> <https://github.com/wjwwood> The tests now pass. If someone could merge
> this for me, I would appreciate it.
>
> Merged both this PR and the one in rclcpp.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ros2/rcl_interfaces/pull/89#issuecomment-601878109>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAH7D6ULHVKOXFZOXRRD36LRIPAXRANCNFSM4LCW7NRA>
> .
>